import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Snake Game</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center bg-gradient-to-br from-[#27272a] via-[#18181b] to-[#171717] text-white">
        <h1 className="p-14 text-6xl font-bold drop-shadow-2xl">Snake Game</h1>
        <div className="flex flex-col items-center justify-center gap-y-4 text-4xl">
          <a
            className="flex w-full flex-col rounded-full border-4 border-[#404040] bg-gradient-to-br from-[#27272a] to-[#18181b] p-5"
            href="/play"
          >
            <button>
              <i className="fa-solid fa-play"></i> Play
            </button>
          </a>
          <a
            className="flex w-full flex-col rounded-full border-4 border-[#404040] bg-gradient-to-br from-[#27272a] to-[#18181b] p-5"
            href="/leaderboard"
          >
            <button>
              <i className="fa-solid fa-trophy"></i> Leaderboard
            </button>
          </a>
        </div>
      </main>
    </>
  );
};

export default Home;
