import { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

interface Ranking {
  name: string;
  score: number;
  id: string;
}

const Leaderboard: NextPage = () => {
  const utils = trpc.useContext();
  const { data } = trpc.rankings.getRankings.useQuery();

  const handleDisplay = (key: number, ranking: Ranking) => {
    if (key == 0) {
      return (
        <div className="flex flex-row justify-between gap-x-20 rounded-3xl bg-yellow-300 px-5 py-2 text-3xl text-black">
          <div className="flex flex-row gap-x-4">
            <h1>{key + 1}</h1>
            <h1>|</h1>
          </div>
          <h1>{ranking.name}</h1>
          <h1>{ranking.score}</h1>
        </div>
      );
    }

    if (key == 1) {
      return (
        <div className="flex flex-row justify-between gap-x-20 rounded-3xl bg-slate-400 px-5 py-2 text-3xl text-black">
          <div className="flex flex-row gap-x-4">
            <h1>{key + 1}</h1>
            <h1>|</h1>
          </div>
          <h1>{ranking.name}</h1>
          <h1>{ranking.score}</h1>
        </div>
      );
    }

    if (key == 2) {
      return (
        <div className="flex flex-row justify-between gap-x-20 rounded-3xl bg-yellow-900 px-5 py-2 text-3xl text-black">
          <div className="flex flex-row gap-x-4">
            <h1>{key + 1}</h1>
            <h1>|</h1>
          </div>
          <h1>{ranking.name}</h1>
          <h1>{ranking.score}</h1>
        </div>
      );
    }

    return (
      <div className="flex flex-row justify-between gap-x-20 rounded-3xl bg-white px-5 py-2 text-3xl text-black">
        <div className="flex flex-row gap-x-4">
          <h1>{key + 1}</h1>
          <h1>|</h1>
        </div>
        <h1>{ranking.name}</h1>
        <h1>{ranking.score}</h1>
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Snake Game</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-w-screen h-full min-h-screen w-full bg-gradient-to-br from-[#27272a] via-[#18181b] to-[#171717] pb-20 text-white">
        <div>
          <a href="/">
            <h1 className="p-5 text-2xl">
              <i className="fa-solid fa-arrow-left"></i> Exit
            </h1>
          </a>
        </div>

        <h1 className="text-center text-6xl font-bold">LEADERBOARD</h1>

        <div className="mr-96 ml-96 mt-10 flex flex-col rounded-3xl border-4 border-[#404040] bg-gradient-to-br from-[#27272a] via-[#18181b] to-[#171717] py-10 font-semibold">
          {data?.map((ranking, i) => {
            return (
              <div key={i} className="px-10 py-4">
                {handleDisplay(i, ranking)}
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
};

export default Leaderboard;
